language: ruby
rvm:
  - 2.3.1
before_install: 
  - gem install bundler -v 1.12.5
  - psql -c 'create database "TaskManagment_test";' -U postgres
script:
  - bundle exec rake test
env:
  - TESTFOLDER=./
 